export default Questions = [
  {
    question: 'Q1 : What Does HTML Stand For?',
    options: [
      'Hyper Text Markup Language',
      'Hypers Tool Markup Language',
      'Home Tool Markup Language',
      'How Text Markup Language',
    ],
    ans: 'Hyper Text Markup Language',
  },
  {
    question: 'Q2 : Who is making the Web standards?',
    options: [
      'Mozilla',
      'The World Wide Web Consortium',
      'Google',
      'Microsoft',
    ],
    ans: 'Google',
  },
  {
    question: 'Q1 : What Does HTML Stand For?',
    options: [
      'Hyper Text Markup Language',
      'Hypers Tool Markup Language',
      'Home Tool Markup Language',
      'How Text Markup Language',
    ],
    ans: 'Hyper Text Markup Language',
  },
  {
    question: 'Q2 : Who is making the Web standards?',
    options: [
      'Mozilla',
      'The World Wide Web Consortium',
      'Google',
      'Microsoft',
    ],
    ans: 'Google',
  },
  //   {
  //     question: 'Q3 : Choose the correct HTML element for the largest heading:',
  //     option1: 'heading',
  //     option2: 'heading2',
  //     option3: "<'h1'>",
  //     option4: 'heading6',
  //     ans: 'ans3',
  //   },
  //   {
  //     question:
  //       'Q4 : What is the correct HTML element for inserting a line break?',
  //     option1: "<'br'>",
  //     option2: 'lb',
  //     option3: 'break',
  //     option4: 'bra',
  //     ans: 'ans1',
  //   },
  //   {
  //     question: 'Q5 : What is the correct HTML for adding a background color?',
  //     option1: "body bg='yellow'",
  //     option2: "<'body style='background-color:yellow;''>",
  //     option3: 'yellow',
  //     option4: "<'body background-color='yellow''>",
  //     ans: 'ans2',
  //   },
  //   {
  //     question: 'Q6 : Choose the correct HTML element to define important text:',
  //     option1: 'i',
  //     option2: "<'strong'>",
  //     option3: 'important',
  //     option4: 'b',
  //     ans: 'ans2',
  //   },
  //   {
  //     question: 'Q7 : Choose the correct HTML element to define emphasized text:',
  //     option1: "<'em'>",
  //     option2: 'i',
  //     option3: 'italic',
  //     option4: 'abr',
  //     ans: 'ans1',
  //   },
  //   {
  //     question: 'Q8 : Which character is used to indicate an end tag?',
  //     option1: '/',
  //     option2: '>',
  //     option3: '*',
  //     option4: '^',
  //     ans: 'ans2',
  //   },
  //   {
  //     question: "Q9 : Which of these elements are all <'table'> elements?",
  //     option1: "<'table'> <'tr'> <'td'>",
  //     option2: "<'table'> <'td'> <'tr'>",
  //     option3: "<'table'> <'tr'> <'tt'>",
  //     option4: "<'thead'> <'body'> <'tt'>",
  //     ans: 'ans1',
  //   },
  //   {
  //     question: 'Q10 : How can you make a numbered list?',
  //     option1: "<'dl'>",
  //     option2: "<'ol'>",
  //     option3: "<'list'>",
  //     option4: "<'ul'>",
  //     ans: 'ans2',
  //   },
];
